server:
  port: 8081
jwt:
  secret: Kx9#vQ2pL7mZr4tYw8nB1cEf6hJs0dGu3iAo5xNe7qM!
  access-token-expiration: 86400000
  refresh-token-expiration: 2592000000
# Spring
spring:
  application:
    # 应用名称
    name: simple-auth
  profiles:
    # 环境配置
    active: dev
  cloud:
    nacos:
      discovery:
        # 服务注册地址
        server-addr: 127.0.0.1:8848
      config:
        # 配置中心地址
        server-addr: 127.0.0.1:8848
        # 配置文件格式
        file-extension: yml
        # 共享配置
        shared-configs:
          - application-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
knife4j:
  enable: true
  setting:
    language: zh_cn
